services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.0
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__RBAC=true
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - /c/Users/hp/OneDrive/Desktop/All_projects/amazon_project/dags:/opt/airflow/dags:ro
      - /c/Users/hp/OneDrive/Desktop/All_projects/amazon_project/data:/opt/airflow/data:ro
    ports:
      - "8080:8080"
    command: standalone

  localstack:
    image: localstack/localstack:3.0
    environment:
      - SERVICES=s3,glue,lambda,kinesis,firehose,emr,redshift,iam
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "4566:4566"
    volumes:
      - ./glue_jobs:/tmp/glue_jobs
      - ./lambda_functions:/tmp/lambda_functions

volumes:
  postgres_data:
